### DISCUSSION TITLE
宫格 nut-grid-item 的内边距 paddding该怎么更改？

### DISCUSSION THREAD

**Discussion by arbureva** [jdf2e/nutui#1739] [General]
宫格 nut-grid-item 的内边距 paddding该怎么更改？
```CSS
.nut-grid-item__content {
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    height: 100%;
    padding: 16px 8px;
    background: #fff;
    border: 0 solid #f5f6f7;
}
```
