### DISCUSSION TITLE
Vue3 覆盖 组件库样式不生效

### DISCUSSION THREAD

**Discussion by richard1015** [jdf2e/nutui#861] [Q&A]
``` css
<style scoped>
:deep(.nut-button) {
  color:red;
}
</style> 
```
vue 官方文档 https://v3.vuejs.org/api/sfc-style.html#deep-selectors
