### ISSUE TITLE
[SECURITY] Arbitrary write access to the repository

### ISSUE THREAD

**Issue by JarLob** [jdf2e/nutui#384]
# GitHub Security Lab (GHSL) Vulnerability Report: `GHSL-2020-287`

The https://github.com/jdf2e/nutui/pull/383 addresses a severe Security issue. It should be merged into `v2-dev` branch **ASAP** and backported to the `master` branch. We have been unsuccessfully trying to access the repository maintainers by publicly available emails since 2020-11-30 and created a pull request asking to provide the security contact in SECURITY.md.

## Summary

The [preview.yml](https://github.com/jdf2e/nutui/blob/v2-dev/.github/workflows/preview.yml) GitHub workflow is vulnerable to unauthorized modification of the base repository or secrets exfiltration from a Pull Request.

## Tested Version

The latest changeset [9d59193](https://github.com/jdf2e/nutui/blob/9d59193d38b2b85baf31747b4d9a000e010893d6/.github/workflows/preview.yml) to the date.

### Issue: Untrusted code is explicitly checked out and run on a Pull Request from a fork

`pull_request_target` was introduced to allow triggered workflows to comment on PRs, label them, assign people, etc.. In order to make it possible the triggered action runner has read/write token for the base repository and the access to secrets. In order to prevent untrusted code from execution it runs in a context of the base repository.

By explicitly checking out and running build script from a fork the untrusted code is running in an environment that is able to push to the base repository and to access secrets.

```yaml
on: pull_request_target
...
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: |
            cnpm install
            npm run build:site
            mv dist/default.html dist/index.html
          dist: site/public
...
```

#### Impact

The vulnerability allows for unauthorized modification of the base repository and secrets exfiltration.

#### Remediation

The workflow should be split into two. The first one triggered on `pull_request` that doesn't have write access to the repository and doesn't have the access to secrets, should build the code and store the results as artifacts. The action should be used in the second workflow that is triggered on [workflow_run](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run) where it can consume the build artifacts without running them and call the action. Until the action is fixed itself the workflow should set the `dist` argument to the downloaded artifacts path and the `build` argument to something like `echo Create sites preview` to prevent the action from running the build script itself.

## Credit

This issue was discovered and reported by GHSL team member [@JarLob (Jaroslav Lobačevski)](https://github.com/JarLob).

## Contact

You can contact the GHSL team at `securitylab@github.com`, please include a reference to `GHSL-2020-287` in any communication regarding this issue.

## Disclosure Policy

Our [disclosure policy](https://securitylab.github.com/disclosures#policy).
