### ISSUE TITLE
[bug]开发小程序时报 [WXSS 文件编译错误]

### ISSUE THREAD

**Issue by Ttou** [jdf2e/nutui#774]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

[示例项目](https://gitee.com/jh_shot/taro-template)

## 预期的行为和实际行为
`3.1.9` 版本会报这个错误， `3.1.8` 是正常的

![image](https://user-images.githubusercontent.com/4298437/138415389-43d5279c-5add-40f4-a713-68f3e0e7dde6.png)

**Comment by Ttou** [comment]
看了下源码，发现是 `style.css` 里的代码引起的：

```css
*{-webkit-tap-highlight-color:rgba(0,0,0,0);-webkit-tap-highlight-color:transparent}
```
